apiVersion: v1
kind: Service
metadata:
  namespace: workshop
  name: backend-service
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 80  # Port on which the service will be exposed within the cluster
      targetPort: 3500  # Port on which the backend application is listening
  type: ClusterIP  # Expose the service internally within the cluster
