apiVersion: v1
kind: Secret
metadata:
  namespace: workshop
  name: mongodb-secrets
type: Opaque
data:
  # Base64 encoded username
  username: <base64-encoded-username> #admin
  # Base64 encoded password
  password: <base64-encoded-password> #password123

